#pragma once

#define COMMANDINDEXMAX		0x400
#define COMMANDSTRINGMAX	0x20
#define COMMANDSHORTSTRMAX	0x10

#define COMMANDWANTPROMPTMAX	0x100
#define COMMANDSUBINDEXMAX		0x100

#define CI_MAKESUBEX(PCOUNT, UCOUNT)	((PCOUNT)+((UCOUNT)<<8))
#define CI_GETPCOUNT(SUBEX)				((SUBEX)&0xff)
#define CI_GETUCOUNT(SUBEX)				((SUBEX)>>8)

enum{
	COMM_NULL = 0,

	_COMM_PUSHCOMMANDBEGIN,

	COMM_PAN,		// enter pan mode
	COMM_ZOOMIN,	// rect zoom

	_COMM_NOLOGCOMMANDBEGIN,
	COMM_DOZOOM,	// mouse wheel
	_COMM_NOLOGCOMMANDEND,

	_COMM_PUSHCOMMANDEND,

	_COMM_INSTANTCOMMANDBEGIN,


	_COMM_INSTANTCOMMANDEND,

	COMM_LINE,
	COMM_BEZIER,

	_COMM_INTERNALBEGIN=COMMANDINDEXMAX,

	COMM_I_COMMAND,
	COMM_I_ADDNODE,
	COMM_I_DELETENODE,
	COMM_I_REPARENTNODE,

	_COMM_INTERNALEND,
};


#define COMMPARAMFLAG_X		0x0001
#define COMMPARAMFLAG_Y		0x0002
//#define COMMPARAMFLAG_XY	0x0003
#define COMMPARAMFLAG_F		0x0010
#define COMMPARAMFLAG_I		0x0020
#define COMMPARAMFLAG_S		0x0040
#define COMMPARAMFLAG_G		0x0100

#define COMMPARAMMAX	16
#define CSI_INIT			0
#define CSI_TERMINAL		-1
#define CSI_FINISH			-2
#define CSI_FINISHCONTINUE	-3
#define CSI_PAUSE			-4
#define CSI_RESUME			-5

// CSP Param
// CSI Step

enum{
	CSP_PAN_OFFSET_XY = 0,
};

enum{
	CSI_PAN_DUMMY=0,
	CSI_PAN_READY,
};

enum{
	CSP_ZOOMIN_B_XY = 0,
	CSP_ZOOMIN_E_XY,
};

enum{
	CSP_DOZOOM_C_XY_SCALE = 0,
};

enum{
	CSI_LINE_DUMMY=0,
	CSI_LINE_WANTX1,
	CSI_LINE_WANTY1,
	CSI_LINE_WANTX2,
	CSI_LINE_WANTY2,
};

enum{
	CSP_LINE_B_XY = 0,
	CSP_LINE_N_XY,
};

// CWP Prompt

enum{
	CWP_NULL=0,
	CWP_X,
	CWP_Y,
	CWP_XY,
	CWP_X_B,
	CWP_Y_B,
	CWP_XY_B,
	CWP_X_E,
	CWP_Y_E,
	CWP_XY_E,
	CWP_X_N,
	CWP_Y_N,
	CWP_XY_N,
	CWP_XOFFSET,
	CWP_YOFFSET,
	CWP_SCALE,
};

// SSC Sub

enum{
	SSC_NULL=0,
	SSC_UNDO,
	SSC_REDO,
	SSC_FINISH,
	SSC_TERMINAL,
};