enum{
	WMUSER_REBUILDTREE=WM_USER+1,
};
enum{
	ID_UI_BUTTON_BEGIN=50000,

	ID_UI_BUTTON_LAYER_BEGIN,
	ID_UI_BUTTON_LAYER_FAKEL,
	ID_UI_BUTTON_LAYER_FAKER,
	ID_UI_BUTTON_LAYER_DUPLICATE,
	ID_UI_BUTTON_LAYER_NEWLAYER,
	ID_UI_BUTTON_LAYER_NEWSUBLAYER,
	ID_UI_BUTTON_LAYER_DELETEITEM,
	ID_UI_BUTTON_LAYER_END,

	ID_UI_BUTTON_HISTORY_BEGIN,
	ID_UI_BUTTON_HISTORY_FAKEL,
	ID_UI_BUTTON_HISTORY_FAKER,
	ID_UI_BUTTON_HISTORY_DELETE,
	ID_UI_BUTTON_HISTORY_SNAPSHOT,
	ID_UI_BUTTON_HISTORY_END,
};